
export const images = [
  {id: 1, image_circle: 'assets/circle-images/circle-image-1.png', image_points: 'assets/point-images/point-image-1.png'},
  {id: 2, image_circle: 'assets/circle-images/circle-image-2.png', image_points: 'assets/point-images/point-image-2.png'},
  {id: 3, image_circle: 'assets/circle-images/circle-image-3.png', image_points: 'assets/point-images/point-image-3.png'},
  {id: 4, image_circle: 'assets/circle-images/circle-image-4.png', image_points: 'assets/point-images/point-image-4.png'},
  {id: 5, image_circle: 'assets/circle-images/circle-image-5.png', image_points: 'assets/point-images/point-image-5.png'},
  {id: 6, image_circle: 'assets/circle-images/circle-image-6.png', image_points: 'assets/point-images/point-image-6.png'},
  {id: 7, image_circle: 'assets/circle-images/circle-image-7.png', image_points: 'assets/point-images/point-image-7.png'},
  {id: 8, image_circle: 'assets/circle-images/circle-image-8.png', image_points: 'assets/point-images/point-image-8.png'},
  {id: 9, image_circle: 'assets/circle-images/circle-image-9.png', image_points: 'assets/point-images/point-image-9.png'},
  {id: 10, image_circle: 'assets/circle-images/circle-image-10.png', image_points: 'assets/point-images/point-image-10.png'},
  {id: 11, image_circle: 'assets/circle-images/circle-image-11.png', image_points: 'assets/point-images/point-image-11.png'},
  {id: 12, image_circle: 'assets/circle-images/circle-image-12.png', image_points: 'assets/point-images/point-image-12.png'},
  {id: 13, image_circle: 'assets/circle-images/circle-image-13.png', image_points: 'assets/point-images/point-image-13.png'},
  {id: 14, image_circle: 'assets/circle-images/circle-image-14.png', image_points: 'assets/point-images/point-image-14.png'},
  {id: 15, image_circle: 'assets/circle-images/circle-image-15.png', image_points: 'assets/point-images/point-image-15.png'},
  {id: 16, image_circle: 'assets/circle-images/circle-image-16.png', image_points: 'assets/point-images/point-image-16.png'},
  {id: 17, image_circle: 'assets/circle-images/circle-image-17.png', image_points: 'assets/point-images/point-image-17.png'},
  {id: 18, image_circle: 'assets/circle-images/circle-image-18.png', image_points: 'assets/point-images/point-image-18.png'},
  {id: 19, image_circle: 'assets/circle-images/circle-image-19.png', image_points: 'assets/point-images/point-image-19.png'},
  {id: 20, image_circle: 'assets/circle-images/circle-image-20.png', image_points: 'assets/point-images/point-image-20.png'},
  {id: 21, image_circle: 'assets/circle-images/circle-image-21.png', image_points: 'assets/point-images/point-image-21.png'},
  {id: 22, image_circle: 'assets/circle-images/circle-image-22.png', image_points: 'assets/point-images/point-image-22.png'},
  {id: 23, image_circle: 'assets/circle-images/circle-image-23.png', image_points: 'assets/point-images/point-image-23.png'},
  {id: 24, image_circle: 'assets/circle-images/circle-image-24.png', image_points: 'assets/point-images/point-image-24.png'},
  {id: 25, image_circle: 'assets/circle-images/circle-image-25.png', image_points: 'assets/point-images/point-image-25.png'},
  {id: 26, image_circle: 'assets/circle-images/circle-image-26.png', image_points: 'assets/point-images/point-image-26.png'},
  {id: 27, image_circle: 'assets/circle-images/circle-image-27.png', image_points: 'assets/point-images/point-image-27.png'},
  {id: 28, image_circle: 'assets/circle-images/circle-image-28.png', image_points: 'assets/point-images/point-image-28.png'},
  {id: 29, image_circle: 'assets/circle-images/circle-image-default.png', image_points: 'assets/point-images/point-image-default.png'}
];